-- Runtime plugin persistence for L5 Self-Extension
-- Stores Python plugins generated by Skill Manager at runtime

CREATE TABLE IF NOT EXISTS runtime_plugins (
    plugin_id TEXT PRIMARY KEY,
    script_name TEXT NOT NULL,
    description TEXT,
    code_content TEXT NOT NULL,
    permissions TEXT DEFAULT '[]',
    created_at INTEGER NOT NULL,
    created_by TEXT,
    generation_number INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_runtime_plugins_active ON runtime_plugins(is_active);
